[package]
name = "neural_net"
version = "0.1.0"
authors = ["Balthazar Potet <balthazarpotet@gmail.com>"]

[dependencies]
itertools = "0.7.4"
rand = "0.4.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.nalgebra]
version = "0.13.0"
features = ["serde-serialize"]